# print a number 1 to 100 ?
# num = 1 
# while num<=100:
#     print(num)
#     num = num +1 
    
#print a number 100 to 1 ?
# num = 100 
# while num>=1:
#     print(num)
#     num = num -1 

#print a table of n number ?
# num = int(input("enter"))
# table = 1
# while table <= 10:
#     print(num*table)
#     table = table + 1
    
# print a list ?
# list = [61,41,551,54,51,4,154,1,541,4,14,1,4,54,48,]
# i = 0
# while i<len(list):
#     print (list[i])
#     i+=1
    
# fruits = ["mango","banana","watermelon","apple"]
# i = 0
# while i<len(fruits):
#     print(fruits[i])
#     i+=1

#print the x number in the tuple ?
num = (141,62,5,1,21,5,621,1,51,1,61,1,5,1,6,5695,)
x = 621
# i = 0
# while i < len(num):
#     if (num[i]==x):
#         print("found",i)
#     i+=1
# index = 0    
# for i in num :
#     if (i==621):
#         print("found",i)
#     # index = index+1
        
#armstrong number
num = "153" 
power = len(num)
ans=0
for i in num :
    ans=ans+int(i)**power
if ans==int(num):
    print("ok")
else:
    print("not ok")
    
    

    
    